name: typescript-playwright-jest
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser name'
        required: false
        default: 'chromium'

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2

      - name: Install Node modules 
        run: npm install

      - name: Run test
        run: xvfb-run --auto-servernum -- npm run tests:chrome      

      - name: Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure-pages
          path: allure-pages

      - name: Create Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: allure-pages
          allure_report: allure-report
          allure_history: allure-history

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-report
          path: allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: allure-pages
          PUBLISH_DIR: allure-history
